Implemented filtering tags from spec.
The reason for filtering is that architecture-dependent tags may lead
to crashes(see below) when parsing specs if current system architecture
differs from the one, mentioned in the architecture dependent tags.

error: No compatible architectures found for build
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gbp/rpm/__init__.py", line 499, in parse_spec
    return SpecFile(specfile)
  File "/usr/lib/python2.7/site-packages/gbp/rpm/__init__.py", line 207, in __init__
    raise GbpError, "RPM error while parsing spec: %s" % err
gbp.errors.GbpError: RPM error while parsing spec: can't parse specfile

Fixes: #301

Change-Id: Ia13c4113c98843fe04abb57288313cc2555c80de